//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IGarageClient {

    getSettings(): Promise<GarageSettings>;

    getOverview(): Promise<GarageOverview>;

    getServices(): Promise<GarageServiceItemDto[]>;

    getEmployees(): Promise<GarageEmployeeItemDto[]>;

    createService(command: CreateGarageServiceCommand): Promise<GarageServiceItem>;

    createEmployee(command: CreateGarageEmployeeCommand): Promise<GarageEmployeeItem>;

    updateSettings(command: UpdateGarageSettingsCommand): Promise<GarageSettings>;

    updateService(command: UpdateGarageServiceCommand): Promise<GarageServiceItem>;

    updateEmployee(command: UpdateGarageEmployeeCommand): Promise<GarageEmployeeItem>;

    deleteService(id: string): Promise<GarageServiceItem>;

    deleteEmployee(id: string): Promise<GarageEmployeeItem>;
}

export class GarageClient implements IGarageClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getSettings(): Promise<GarageSettings> {
        let url_ = this.baseUrl + "/api/Garage/GetSettings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSettings(_response);
        });
    }

    protected processGetSettings(response: Response): Promise<GarageSettings> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageSettings.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageSettings>(null as any);
    }

    getOverview(): Promise<GarageOverview> {
        let url_ = this.baseUrl + "/api/Garage/GetOverview";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetOverview(_response);
        });
    }

    protected processGetOverview(response: Response): Promise<GarageOverview> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageOverview.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageOverview>(null as any);
    }

    getServices(): Promise<GarageServiceItemDto[]> {
        let url_ = this.baseUrl + "/api/Garage/GetServices";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetServices(_response);
        });
    }

    protected processGetServices(response: Response): Promise<GarageServiceItemDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GarageServiceItemDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageServiceItemDto[]>(null as any);
    }

    getEmployees(): Promise<GarageEmployeeItemDto[]> {
        let url_ = this.baseUrl + "/api/Garage/GetEmployees";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetEmployees(_response);
        });
    }

    protected processGetEmployees(response: Response): Promise<GarageEmployeeItemDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GarageEmployeeItemDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageEmployeeItemDto[]>(null as any);
    }

    createService(command: CreateGarageServiceCommand): Promise<GarageServiceItem> {
        let url_ = this.baseUrl + "/api/Garage/CreateService";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateService(_response);
        });
    }

    protected processCreateService(response: Response): Promise<GarageServiceItem> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageServiceItem.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageServiceItem>(null as any);
    }

    createEmployee(command: CreateGarageEmployeeCommand): Promise<GarageEmployeeItem> {
        let url_ = this.baseUrl + "/api/Garage/CreateEmployee";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateEmployee(_response);
        });
    }

    protected processCreateEmployee(response: Response): Promise<GarageEmployeeItem> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageEmployeeItem.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageEmployeeItem>(null as any);
    }

    updateSettings(command: UpdateGarageSettingsCommand): Promise<GarageSettings> {
        let url_ = this.baseUrl + "/api/Garage/UpdateSettings";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateSettings(_response);
        });
    }

    protected processUpdateSettings(response: Response): Promise<GarageSettings> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageSettings.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageSettings>(null as any);
    }

    updateService(command: UpdateGarageServiceCommand): Promise<GarageServiceItem> {
        let url_ = this.baseUrl + "/api/Garage/UpdateService";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateService(_response);
        });
    }

    protected processUpdateService(response: Response): Promise<GarageServiceItem> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageServiceItem.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageServiceItem>(null as any);
    }

    updateEmployee(command: UpdateGarageEmployeeCommand): Promise<GarageEmployeeItem> {
        let url_ = this.baseUrl + "/api/Garage/UpdateEmployee";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateEmployee(_response);
        });
    }

    protected processUpdateEmployee(response: Response): Promise<GarageEmployeeItem> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageEmployeeItem.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageEmployeeItem>(null as any);
    }

    deleteService(id: string): Promise<GarageServiceItem> {
        let url_ = this.baseUrl + "/api/Garage/DeleteService/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "PUT",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteService(_response);
        });
    }

    protected processDeleteService(response: Response): Promise<GarageServiceItem> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageServiceItem.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageServiceItem>(null as any);
    }

    deleteEmployee(id: string): Promise<GarageEmployeeItem> {
        let url_ = this.baseUrl + "/api/Garage/DeleteEmployee/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "PUT",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteEmployee(_response);
        });
    }

    protected processDeleteEmployee(response: Response): Promise<GarageEmployeeItem> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageEmployeeItem.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageEmployeeItem>(null as any);
    }
}

export interface IGarageRegisterClient {

    create(command: CreateGarageCommand): Promise<GarageSettings>;
}

export class GarageRegisterClient implements IGarageRegisterClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    create(command: CreateGarageCommand): Promise<GarageSettings> {
        let url_ = this.baseUrl + "/api/GarageRegister/Create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<GarageSettings> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GarageSettings.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BadRequestResponse.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GarageSettings>(null as any);
    }
}

export interface IVehicleClient {

    searchVehicle(licensePlate: string | null | undefined): Promise<LicencePlateBriefResponse>;

    getVehicleInformation(licensePlate: string | null | undefined): Promise<VehicleInformationResponse>;
}

export class VehicleClient implements IVehicleClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    searchVehicle(licensePlate: string | null | undefined): Promise<LicencePlateBriefResponse> {
        let url_ = this.baseUrl + "/api/Vehicle/search?";
        if (licensePlate !== undefined && licensePlate !== null)
            url_ += "licensePlate=" + encodeURIComponent("" + licensePlate) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSearchVehicle(_response);
        });
    }

    protected processSearchVehicle(response: Response): Promise<LicencePlateBriefResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = LicencePlateBriefResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LicencePlateBriefResponse>(null as any);
    }

    getVehicleInformation(licensePlate: string | null | undefined): Promise<VehicleInformationResponse> {
        let url_ = this.baseUrl + "/api/Vehicle/information?";
        if (licensePlate !== undefined && licensePlate !== null)
            url_ += "licensePlate=" + encodeURIComponent("" + licensePlate) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetVehicleInformation(_response);
        });
    }

    protected processGetVehicleInformation(response: Response): Promise<VehicleInformationResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = VehicleInformationResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<VehicleInformationResponse>(null as any);
    }
}

export interface IWeatherForecastClient {

    get(): Promise<WeatherForecast[]>;
}

export class WeatherForecastClient implements IWeatherForecastClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    get(): Promise<WeatherForecast[]> {
        let url_ = this.baseUrl + "/api/WeatherForecast";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<WeatherForecast[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(WeatherForecast.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WeatherForecast[]>(null as any);
    }
}

export class GarageSettings implements IGarageSettings {
    name?: string;
    email?: string;
    phoneNumber?: string;
    whatsAppNumber?: string;
    location?: GarageLocationItem;
    bankingDetails?: GarageBankingDetailsItem;
    servicesSettings?: GarageServicesSettingsItem;
    contacts?: ContactItem[];

    constructor(data?: IGarageSettings) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.email = _data["email"];
            this.phoneNumber = _data["phoneNumber"];
            this.whatsAppNumber = _data["whatsAppNumber"];
            this.location = _data["location"] ? GarageLocationItem.fromJS(_data["location"]) : <any>undefined;
            this.bankingDetails = _data["bankingDetails"] ? GarageBankingDetailsItem.fromJS(_data["bankingDetails"]) : <any>undefined;
            this.servicesSettings = _data["servicesSettings"] ? GarageServicesSettingsItem.fromJS(_data["servicesSettings"]) : <any>undefined;
            if (Array.isArray(_data["contacts"])) {
                this.contacts = [] as any;
                for (let item of _data["contacts"])
                    this.contacts!.push(ContactItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GarageSettings {
        data = typeof data === 'object' ? data : {};
        let result = new GarageSettings();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["email"] = this.email;
        data["phoneNumber"] = this.phoneNumber;
        data["whatsAppNumber"] = this.whatsAppNumber;
        data["location"] = this.location ? this.location.toJSON() : <any>undefined;
        data["bankingDetails"] = this.bankingDetails ? this.bankingDetails.toJSON() : <any>undefined;
        data["servicesSettings"] = this.servicesSettings ? this.servicesSettings.toJSON() : <any>undefined;
        if (Array.isArray(this.contacts)) {
            data["contacts"] = [];
            for (let item of this.contacts)
                data["contacts"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGarageSettings {
    name?: string;
    email?: string;
    phoneNumber?: string;
    whatsAppNumber?: string;
    location?: GarageLocationItem;
    bankingDetails?: GarageBankingDetailsItem;
    servicesSettings?: GarageServicesSettingsItem;
    contacts?: ContactItem[];
}

export abstract class BaseEntity implements IBaseEntity {
    id?: string;
    domainEvents?: BaseEvent[];

    constructor(data?: IBaseEntity) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            if (Array.isArray(_data["domainEvents"])) {
                this.domainEvents = [] as any;
                for (let item of _data["domainEvents"])
                    this.domainEvents!.push(BaseEvent.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BaseEntity {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseEntity' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        if (Array.isArray(this.domainEvents)) {
            data["domainEvents"] = [];
            for (let item of this.domainEvents)
                data["domainEvents"].push(item.toJSON());
        }
        return data;
    }
}

export interface IBaseEntity {
    id?: string;
    domainEvents?: BaseEvent[];
}

export class GarageLocationItem extends BaseEntity implements IGarageLocationItem {
    address?: string;
    city?: string;
    postalCode?: string;
    country?: string;
    longitude?: number;
    latitude?: number;

    constructor(data?: IGarageLocationItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.address = _data["address"];
            this.city = _data["city"];
            this.postalCode = _data["postalCode"];
            this.country = _data["country"];
            this.longitude = _data["longitude"];
            this.latitude = _data["latitude"];
        }
    }

    static fromJS(data: any): GarageLocationItem {
        data = typeof data === 'object' ? data : {};
        let result = new GarageLocationItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["address"] = this.address;
        data["city"] = this.city;
        data["postalCode"] = this.postalCode;
        data["country"] = this.country;
        data["longitude"] = this.longitude;
        data["latitude"] = this.latitude;
        super.toJSON(data);
        return data;
    }
}

export interface IGarageLocationItem extends IBaseEntity {
    address?: string;
    city?: string;
    postalCode?: string;
    country?: string;
    longitude?: number;
    latitude?: number;
}

export abstract class BaseEvent implements IBaseEvent {

    constructor(data?: IBaseEvent) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): BaseEvent {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseEvent' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IBaseEvent {
}

export class GarageBankingDetailsItem extends BaseEntity implements IGarageBankingDetailsItem {
    bankName?: string;
    kvKNumber?: string;
    accountHolderName?: string;
    iban?: string;

    constructor(data?: IGarageBankingDetailsItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.bankName = _data["bankName"];
            this.kvKNumber = _data["kvKNumber"];
            this.accountHolderName = _data["accountHolderName"];
            this.iban = _data["iban"];
        }
    }

    static fromJS(data: any): GarageBankingDetailsItem {
        data = typeof data === 'object' ? data : {};
        let result = new GarageBankingDetailsItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["bankName"] = this.bankName;
        data["kvKNumber"] = this.kvKNumber;
        data["accountHolderName"] = this.accountHolderName;
        data["iban"] = this.iban;
        super.toJSON(data);
        return data;
    }
}

export interface IGarageBankingDetailsItem extends IBaseEntity {
    bankName?: string;
    kvKNumber?: string;
    accountHolderName?: string;
    iban?: string;
}

export class GarageServicesSettingsItem extends BaseEntity implements IGarageServicesSettingsItem {
    maxAutomaticPlannedOrders?: number;
    trySendMailOnNewOrders?: boolean;
    trySendWhatsappMessagOnNewOrders?: boolean;
    isDeliveryEnabled?: boolean;
    isAuthohelperDeliveryEnabled?: boolean;
    deliveryPrice?: number;
    maxAutomaticPlannedDeliveries?: number;

    constructor(data?: IGarageServicesSettingsItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.maxAutomaticPlannedOrders = _data["maxAutomaticPlannedOrders"];
            this.trySendMailOnNewOrders = _data["trySendMailOnNewOrders"];
            this.trySendWhatsappMessagOnNewOrders = _data["trySendWhatsappMessagOnNewOrders"];
            this.isDeliveryEnabled = _data["isDeliveryEnabled"];
            this.isAuthohelperDeliveryEnabled = _data["isAuthohelperDeliveryEnabled"];
            this.deliveryPrice = _data["deliveryPrice"];
            this.maxAutomaticPlannedDeliveries = _data["maxAutomaticPlannedDeliveries"];
        }
    }

    static fromJS(data: any): GarageServicesSettingsItem {
        data = typeof data === 'object' ? data : {};
        let result = new GarageServicesSettingsItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["maxAutomaticPlannedOrders"] = this.maxAutomaticPlannedOrders;
        data["trySendMailOnNewOrders"] = this.trySendMailOnNewOrders;
        data["trySendWhatsappMessagOnNewOrders"] = this.trySendWhatsappMessagOnNewOrders;
        data["isDeliveryEnabled"] = this.isDeliveryEnabled;
        data["isAuthohelperDeliveryEnabled"] = this.isAuthohelperDeliveryEnabled;
        data["deliveryPrice"] = this.deliveryPrice;
        data["maxAutomaticPlannedDeliveries"] = this.maxAutomaticPlannedDeliveries;
        super.toJSON(data);
        return data;
    }
}

export interface IGarageServicesSettingsItem extends IBaseEntity {
    maxAutomaticPlannedOrders?: number;
    trySendMailOnNewOrders?: boolean;
    trySendWhatsappMessagOnNewOrders?: boolean;
    isDeliveryEnabled?: boolean;
    isAuthohelperDeliveryEnabled?: boolean;
    deliveryPrice?: number;
    maxAutomaticPlannedDeliveries?: number;
}

export class ContactItem extends BaseEntity implements IContactItem {
    fullName!: string;
    phoneNumber?: string;
    email?: string;

    constructor(data?: IContactItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.fullName = _data["fullName"];
            this.phoneNumber = _data["phoneNumber"];
            this.email = _data["email"];
        }
    }

    static fromJS(data: any): ContactItem {
        data = typeof data === 'object' ? data : {};
        let result = new ContactItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fullName"] = this.fullName;
        data["phoneNumber"] = this.phoneNumber;
        data["email"] = this.email;
        super.toJSON(data);
        return data;
    }
}

export interface IContactItem extends IBaseEntity {
    fullName: string;
    phoneNumber?: string;
    email?: string;
}

export class GarageOverview implements IGarageOverview {
    name?: string;
    vehicles?: VehicleItem[];

    constructor(data?: IGarageOverview) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            if (Array.isArray(_data["vehicles"])) {
                this.vehicles = [] as any;
                for (let item of _data["vehicles"])
                    this.vehicles!.push(VehicleItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GarageOverview {
        data = typeof data === 'object' ? data : {};
        let result = new GarageOverview();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        if (Array.isArray(this.vehicles)) {
            data["vehicles"] = [];
            for (let item of this.vehicles)
                data["vehicles"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGarageOverview {
    name?: string;
    vehicles?: VehicleItem[];
}

export abstract class BaseAuditableEntity extends BaseEntity implements IBaseAuditableEntity {
    created?: Date;
    createdBy?: string | undefined;
    lastModified?: Date | undefined;
    lastModifiedBy?: string | undefined;

    constructor(data?: IBaseAuditableEntity) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.created = _data["created"] ? new Date(_data["created"].toString()) : <any>undefined;
            this.createdBy = _data["createdBy"];
            this.lastModified = _data["lastModified"] ? new Date(_data["lastModified"].toString()) : <any>undefined;
            this.lastModifiedBy = _data["lastModifiedBy"];
        }
    }

    static fromJS(data: any): BaseAuditableEntity {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'BaseAuditableEntity' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["created"] = this.created ? this.created.toISOString() : <any>undefined;
        data["createdBy"] = this.createdBy;
        data["lastModified"] = this.lastModified ? this.lastModified.toISOString() : <any>undefined;
        data["lastModifiedBy"] = this.lastModifiedBy;
        super.toJSON(data);
        return data;
    }
}

export interface IBaseAuditableEntity extends IBaseEntity {
    created?: Date;
    createdBy?: string | undefined;
    lastModified?: Date | undefined;
    lastModifiedBy?: string | undefined;
}

export class VehicleItem extends BaseAuditableEntity implements IVehicleItem {
    licensePlate?: string;
    model?: string;
    brand?: string;
    registrationDate?: Date;
    vehicleOwner?: VehicleOwnerItem;

    constructor(data?: IVehicleItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.licensePlate = _data["licensePlate"];
            this.model = _data["model"];
            this.brand = _data["brand"];
            this.registrationDate = _data["registrationDate"] ? new Date(_data["registrationDate"].toString()) : <any>undefined;
            this.vehicleOwner = _data["vehicleOwner"] ? VehicleOwnerItem.fromJS(_data["vehicleOwner"]) : <any>undefined;
        }
    }

    static fromJS(data: any): VehicleItem {
        data = typeof data === 'object' ? data : {};
        let result = new VehicleItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["licensePlate"] = this.licensePlate;
        data["model"] = this.model;
        data["brand"] = this.brand;
        data["registrationDate"] = this.registrationDate ? this.registrationDate.toISOString() : <any>undefined;
        data["vehicleOwner"] = this.vehicleOwner ? this.vehicleOwner.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IVehicleItem extends IBaseAuditableEntity {
    licensePlate?: string;
    model?: string;
    brand?: string;
    registrationDate?: Date;
    vehicleOwner?: VehicleOwnerItem;
}

export class VehicleOwnerItem extends BaseAuditableEntity implements IVehicleOwnerItem {
    fullName!: string;
    phoneNumber?: string;
    email?: string;

    constructor(data?: IVehicleOwnerItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.fullName = _data["fullName"];
            this.phoneNumber = _data["phoneNumber"];
            this.email = _data["email"];
        }
    }

    static fromJS(data: any): VehicleOwnerItem {
        data = typeof data === 'object' ? data : {};
        let result = new VehicleOwnerItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fullName"] = this.fullName;
        data["phoneNumber"] = this.phoneNumber;
        data["email"] = this.email;
        super.toJSON(data);
        return data;
    }
}

export interface IVehicleOwnerItem extends IBaseAuditableEntity {
    fullName: string;
    phoneNumber?: string;
    email?: string;
}

export class GarageServiceItemDto implements IGarageServiceItemDto {
    id?: string;
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;
    status?: number;

    constructor(data?: IGarageServiceItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.type = _data["type"];
            this.description = _data["description"];
            this.durationInMinutes = _data["durationInMinutes"];
            this.price = _data["price"];
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): GarageServiceItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new GarageServiceItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["type"] = this.type;
        data["description"] = this.description;
        data["durationInMinutes"] = this.durationInMinutes;
        data["price"] = this.price;
        data["status"] = this.status;
        return data;
    }
}

export interface IGarageServiceItemDto {
    id?: string;
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;
    status?: number;
}

export enum GarageServiceType {
    Other = 0,
    Inspection = 1,
    SmallMaintenance = 2,
    GreatMaintenance = 3,
    AirConditioningService = 4,
    SeasonalTireChange = 5,
}

export class GarageEmployeeItemDto implements IGarageEmployeeItemDto {
    id?: string;
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItem[];
    workExperiences?: GarageEmployeeWorkExperienceItem[];

    constructor(data?: IGarageEmployeeItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.isActive = _data["isActive"];
            this.contact = _data["contact"] ? ContactItem.fromJS(_data["contact"]) : <any>undefined;
            if (Array.isArray(_data["workSchema"])) {
                this.workSchema = [] as any;
                for (let item of _data["workSchema"])
                    this.workSchema!.push(GarageEmployeeWorkSchemaItem.fromJS(item));
            }
            if (Array.isArray(_data["workExperiences"])) {
                this.workExperiences = [] as any;
                for (let item of _data["workExperiences"])
                    this.workExperiences!.push(GarageEmployeeWorkExperienceItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GarageEmployeeItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new GarageEmployeeItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["isActive"] = this.isActive;
        data["contact"] = this.contact ? this.contact.toJSON() : <any>undefined;
        if (Array.isArray(this.workSchema)) {
            data["workSchema"] = [];
            for (let item of this.workSchema)
                data["workSchema"].push(item.toJSON());
        }
        if (Array.isArray(this.workExperiences)) {
            data["workExperiences"] = [];
            for (let item of this.workExperiences)
                data["workExperiences"].push(item.toJSON());
        }
        return data;
    }
}

export interface IGarageEmployeeItemDto {
    id?: string;
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItem[];
    workExperiences?: GarageEmployeeWorkExperienceItem[];
}

export class GarageEmployeeWorkSchemaItem extends BaseEntity implements IGarageEmployeeWorkSchemaItem {
    employeeId!: string;
    weekOfYear?: number;
    dayOfWeek!: number;
    startTime!: Date;
    endTime!: Date;
    notes?: string;

    constructor(data?: IGarageEmployeeWorkSchemaItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.employeeId = _data["employeeId"];
            this.weekOfYear = _data["weekOfYear"];
            this.dayOfWeek = _data["dayOfWeek"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.notes = _data["notes"];
        }
    }

    static fromJS(data: any): GarageEmployeeWorkSchemaItem {
        data = typeof data === 'object' ? data : {};
        let result = new GarageEmployeeWorkSchemaItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["employeeId"] = this.employeeId;
        data["weekOfYear"] = this.weekOfYear;
        data["dayOfWeek"] = this.dayOfWeek;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["notes"] = this.notes;
        super.toJSON(data);
        return data;
    }
}

export interface IGarageEmployeeWorkSchemaItem extends IBaseEntity {
    employeeId: string;
    weekOfYear?: number;
    dayOfWeek: number;
    startTime: Date;
    endTime: Date;
    notes?: string;
}

export class GarageEmployeeWorkExperienceItem extends BaseEntity implements IGarageEmployeeWorkExperienceItem {
    employeeId!: string;
    serviceId!: string;
    description!: string;

    constructor(data?: IGarageEmployeeWorkExperienceItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.employeeId = _data["employeeId"];
            this.serviceId = _data["serviceId"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): GarageEmployeeWorkExperienceItem {
        data = typeof data === 'object' ? data : {};
        let result = new GarageEmployeeWorkExperienceItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["employeeId"] = this.employeeId;
        data["serviceId"] = this.serviceId;
        data["description"] = this.description;
        super.toJSON(data);
        return data;
    }
}

export interface IGarageEmployeeWorkExperienceItem extends IBaseEntity {
    employeeId: string;
    serviceId: string;
    description: string;
}

export class GarageServiceItem extends BaseAuditableEntity implements IGarageServiceItem {
    userId?: string;
    garageId?: string;
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;
    status?: number;

    constructor(data?: IGarageServiceItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.userId = _data["userId"];
            this.garageId = _data["garageId"];
            this.type = _data["type"];
            this.description = _data["description"];
            this.durationInMinutes = _data["durationInMinutes"];
            this.price = _data["price"];
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): GarageServiceItem {
        data = typeof data === 'object' ? data : {};
        let result = new GarageServiceItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["garageId"] = this.garageId;
        data["type"] = this.type;
        data["description"] = this.description;
        data["durationInMinutes"] = this.durationInMinutes;
        data["price"] = this.price;
        data["status"] = this.status;
        super.toJSON(data);
        return data;
    }
}

export interface IGarageServiceItem extends IBaseAuditableEntity {
    userId?: string;
    garageId?: string;
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;
    status?: number;
}

export class CreateGarageServiceCommand implements ICreateGarageServiceCommand {
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;

    constructor(data?: ICreateGarageServiceCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.description = _data["description"];
            this.durationInMinutes = _data["durationInMinutes"];
            this.price = _data["price"];
        }
    }

    static fromJS(data: any): CreateGarageServiceCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CreateGarageServiceCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["description"] = this.description;
        data["durationInMinutes"] = this.durationInMinutes;
        data["price"] = this.price;
        return data;
    }
}

export interface ICreateGarageServiceCommand {
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;
}

export class GarageEmployeeItem extends BaseAuditableEntity implements IGarageEmployeeItem {
    userId?: string;
    garageId?: string;
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItem[];
    workExperiences?: GarageEmployeeWorkExperienceItem[];

    constructor(data?: IGarageEmployeeItem) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.userId = _data["userId"];
            this.garageId = _data["garageId"];
            this.isActive = _data["isActive"];
            this.contact = _data["contact"] ? ContactItem.fromJS(_data["contact"]) : <any>undefined;
            if (Array.isArray(_data["workSchema"])) {
                this.workSchema = [] as any;
                for (let item of _data["workSchema"])
                    this.workSchema!.push(GarageEmployeeWorkSchemaItem.fromJS(item));
            }
            if (Array.isArray(_data["workExperiences"])) {
                this.workExperiences = [] as any;
                for (let item of _data["workExperiences"])
                    this.workExperiences!.push(GarageEmployeeWorkExperienceItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GarageEmployeeItem {
        data = typeof data === 'object' ? data : {};
        let result = new GarageEmployeeItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["garageId"] = this.garageId;
        data["isActive"] = this.isActive;
        data["contact"] = this.contact ? this.contact.toJSON() : <any>undefined;
        if (Array.isArray(this.workSchema)) {
            data["workSchema"] = [];
            for (let item of this.workSchema)
                data["workSchema"].push(item.toJSON());
        }
        if (Array.isArray(this.workExperiences)) {
            data["workExperiences"] = [];
            for (let item of this.workExperiences)
                data["workExperiences"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGarageEmployeeItem extends IBaseAuditableEntity {
    userId?: string;
    garageId?: string;
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItem[];
    workExperiences?: GarageEmployeeWorkExperienceItem[];
}

export class CreateGarageEmployeeCommand implements ICreateGarageEmployeeCommand {
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItemDto[];
    workExperiences?: GarageEmployeeWorkExperienceItemDto[];

    constructor(data?: ICreateGarageEmployeeCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isActive = _data["isActive"];
            this.contact = _data["contact"] ? ContactItem.fromJS(_data["contact"]) : <any>undefined;
            if (Array.isArray(_data["workSchema"])) {
                this.workSchema = [] as any;
                for (let item of _data["workSchema"])
                    this.workSchema!.push(GarageEmployeeWorkSchemaItemDto.fromJS(item));
            }
            if (Array.isArray(_data["workExperiences"])) {
                this.workExperiences = [] as any;
                for (let item of _data["workExperiences"])
                    this.workExperiences!.push(GarageEmployeeWorkExperienceItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CreateGarageEmployeeCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CreateGarageEmployeeCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isActive"] = this.isActive;
        data["contact"] = this.contact ? this.contact.toJSON() : <any>undefined;
        if (Array.isArray(this.workSchema)) {
            data["workSchema"] = [];
            for (let item of this.workSchema)
                data["workSchema"].push(item.toJSON());
        }
        if (Array.isArray(this.workExperiences)) {
            data["workExperiences"] = [];
            for (let item of this.workExperiences)
                data["workExperiences"].push(item.toJSON());
        }
        return data;
    }
}

export interface ICreateGarageEmployeeCommand {
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItemDto[];
    workExperiences?: GarageEmployeeWorkExperienceItemDto[];
}

export class GarageEmployeeWorkSchemaItemDto implements IGarageEmployeeWorkSchemaItemDto {
    weekOfYear?: number;
    dayOfWeek!: number;
    startTime!: Date;
    endTime!: Date;
    notes?: string;

    constructor(data?: IGarageEmployeeWorkSchemaItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.weekOfYear = _data["weekOfYear"];
            this.dayOfWeek = _data["dayOfWeek"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.notes = _data["notes"];
        }
    }

    static fromJS(data: any): GarageEmployeeWorkSchemaItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new GarageEmployeeWorkSchemaItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["weekOfYear"] = this.weekOfYear;
        data["dayOfWeek"] = this.dayOfWeek;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["notes"] = this.notes;
        return data;
    }
}

export interface IGarageEmployeeWorkSchemaItemDto {
    weekOfYear?: number;
    dayOfWeek: number;
    startTime: Date;
    endTime: Date;
    notes?: string;
}

export class GarageEmployeeWorkExperienceItemDto implements IGarageEmployeeWorkExperienceItemDto {
    serviceId!: string;
    description!: string;

    constructor(data?: IGarageEmployeeWorkExperienceItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.serviceId = _data["serviceId"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): GarageEmployeeWorkExperienceItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new GarageEmployeeWorkExperienceItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["serviceId"] = this.serviceId;
        data["description"] = this.description;
        return data;
    }
}

export interface IGarageEmployeeWorkExperienceItemDto {
    serviceId: string;
    description: string;
}

export class UpdateGarageSettingsCommand implements IUpdateGarageSettingsCommand {
    name?: string;
    phoneNumber?: string;
    whatsAppNumber?: string;
    email?: string;
    location?: GarageLocationItem;
    bankingDetails?: GarageBankingDetailsItem;
    servicesSettings?: GarageServicesSettingsItem;

    constructor(data?: IUpdateGarageSettingsCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.phoneNumber = _data["phoneNumber"];
            this.whatsAppNumber = _data["whatsAppNumber"];
            this.email = _data["email"];
            this.location = _data["location"] ? GarageLocationItem.fromJS(_data["location"]) : <any>undefined;
            this.bankingDetails = _data["bankingDetails"] ? GarageBankingDetailsItem.fromJS(_data["bankingDetails"]) : <any>undefined;
            this.servicesSettings = _data["servicesSettings"] ? GarageServicesSettingsItem.fromJS(_data["servicesSettings"]) : <any>undefined;
        }
    }

    static fromJS(data: any): UpdateGarageSettingsCommand {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateGarageSettingsCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["phoneNumber"] = this.phoneNumber;
        data["whatsAppNumber"] = this.whatsAppNumber;
        data["email"] = this.email;
        data["location"] = this.location ? this.location.toJSON() : <any>undefined;
        data["bankingDetails"] = this.bankingDetails ? this.bankingDetails.toJSON() : <any>undefined;
        data["servicesSettings"] = this.servicesSettings ? this.servicesSettings.toJSON() : <any>undefined;
        return data;
    }
}

export interface IUpdateGarageSettingsCommand {
    name?: string;
    phoneNumber?: string;
    whatsAppNumber?: string;
    email?: string;
    location?: GarageLocationItem;
    bankingDetails?: GarageBankingDetailsItem;
    servicesSettings?: GarageServicesSettingsItem;
}

export class UpdateGarageServiceCommand implements IUpdateGarageServiceCommand {
    id?: string;
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;

    constructor(data?: IUpdateGarageServiceCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.type = _data["type"];
            this.description = _data["description"];
            this.durationInMinutes = _data["durationInMinutes"];
            this.price = _data["price"];
        }
    }

    static fromJS(data: any): UpdateGarageServiceCommand {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateGarageServiceCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["type"] = this.type;
        data["description"] = this.description;
        data["durationInMinutes"] = this.durationInMinutes;
        data["price"] = this.price;
        return data;
    }
}

export interface IUpdateGarageServiceCommand {
    id?: string;
    type?: GarageServiceType;
    description?: string;
    durationInMinutes?: number;
    price?: number;
}

export class UpdateGarageEmployeeCommand implements IUpdateGarageEmployeeCommand {
    id?: string;
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItemDto[];
    workExperiences?: GarageEmployeeWorkExperienceItemDto[];

    constructor(data?: IUpdateGarageEmployeeCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.isActive = _data["isActive"];
            this.contact = _data["contact"] ? ContactItem.fromJS(_data["contact"]) : <any>undefined;
            if (Array.isArray(_data["workSchema"])) {
                this.workSchema = [] as any;
                for (let item of _data["workSchema"])
                    this.workSchema!.push(GarageEmployeeWorkSchemaItemDto.fromJS(item));
            }
            if (Array.isArray(_data["workExperiences"])) {
                this.workExperiences = [] as any;
                for (let item of _data["workExperiences"])
                    this.workExperiences!.push(GarageEmployeeWorkExperienceItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UpdateGarageEmployeeCommand {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateGarageEmployeeCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["isActive"] = this.isActive;
        data["contact"] = this.contact ? this.contact.toJSON() : <any>undefined;
        if (Array.isArray(this.workSchema)) {
            data["workSchema"] = [];
            for (let item of this.workSchema)
                data["workSchema"].push(item.toJSON());
        }
        if (Array.isArray(this.workExperiences)) {
            data["workExperiences"] = [];
            for (let item of this.workExperiences)
                data["workExperiences"].push(item.toJSON());
        }
        return data;
    }
}

export interface IUpdateGarageEmployeeCommand {
    id?: string;
    isActive?: boolean;
    contact?: ContactItem;
    workSchema?: GarageEmployeeWorkSchemaItemDto[];
    workExperiences?: GarageEmployeeWorkExperienceItemDto[];
}

export class BadRequestResponse implements IBadRequestResponse {
    type?: string;
    title?: string;
    status?: number;
    errors?: { [key: string]: string; };

    constructor(data?: IBadRequestResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            if (_data["errors"]) {
                this.errors = {} as any;
                for (let key in _data["errors"]) {
                    if (_data["errors"].hasOwnProperty(key))
                        (<any>this.errors)![key] = _data["errors"][key];
                }
            }
        }
    }

    static fromJS(data: any): BadRequestResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BadRequestResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        if (this.errors) {
            data["errors"] = {};
            for (let key in this.errors) {
                if (this.errors.hasOwnProperty(key))
                    (<any>data["errors"])[key] = (<any>this.errors)[key];
            }
        }
        return data;
    }
}

export interface IBadRequestResponse {
    type?: string;
    title?: string;
    status?: number;
    errors?: { [key: string]: string; };
}

export class CreateGarageCommand implements ICreateGarageCommand {
    name?: string;
    phoneNumber?: string;
    whatsAppNumber?: string;
    email?: string;
    location?: BriefLocationDto;
    bankingDetails?: BriefBankingDetailsDto;

    constructor(data?: ICreateGarageCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.phoneNumber = _data["phoneNumber"];
            this.whatsAppNumber = _data["whatsAppNumber"];
            this.email = _data["email"];
            this.location = _data["location"] ? BriefLocationDto.fromJS(_data["location"]) : <any>undefined;
            this.bankingDetails = _data["bankingDetails"] ? BriefBankingDetailsDto.fromJS(_data["bankingDetails"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CreateGarageCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CreateGarageCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["phoneNumber"] = this.phoneNumber;
        data["whatsAppNumber"] = this.whatsAppNumber;
        data["email"] = this.email;
        data["location"] = this.location ? this.location.toJSON() : <any>undefined;
        data["bankingDetails"] = this.bankingDetails ? this.bankingDetails.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICreateGarageCommand {
    name?: string;
    phoneNumber?: string;
    whatsAppNumber?: string;
    email?: string;
    location?: BriefLocationDto;
    bankingDetails?: BriefBankingDetailsDto;
}

export class BriefLocationDto implements IBriefLocationDto {
    address?: string;
    postalCode?: string;
    city?: string;
    country?: string;
    longitude?: number;
    latitude?: number;

    constructor(data?: IBriefLocationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.address = _data["address"];
            this.postalCode = _data["postalCode"];
            this.city = _data["city"];
            this.country = _data["country"];
            this.longitude = _data["longitude"];
            this.latitude = _data["latitude"];
        }
    }

    static fromJS(data: any): BriefLocationDto {
        data = typeof data === 'object' ? data : {};
        let result = new BriefLocationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["address"] = this.address;
        data["postalCode"] = this.postalCode;
        data["city"] = this.city;
        data["country"] = this.country;
        data["longitude"] = this.longitude;
        data["latitude"] = this.latitude;
        return data;
    }
}

export interface IBriefLocationDto {
    address?: string;
    postalCode?: string;
    city?: string;
    country?: string;
    longitude?: number;
    latitude?: number;
}

export class BriefBankingDetailsDto implements IBriefBankingDetailsDto {
    bankName?: string;
    kvKNumber?: string;
    accountHolderName?: string;
    iban?: string;

    constructor(data?: IBriefBankingDetailsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.bankName = _data["bankName"];
            this.kvKNumber = _data["kvKNumber"];
            this.accountHolderName = _data["accountHolderName"];
            this.iban = _data["iban"];
        }
    }

    static fromJS(data: any): BriefBankingDetailsDto {
        data = typeof data === 'object' ? data : {};
        let result = new BriefBankingDetailsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["bankName"] = this.bankName;
        data["kvKNumber"] = this.kvKNumber;
        data["accountHolderName"] = this.accountHolderName;
        data["iban"] = this.iban;
        return data;
    }
}

export interface IBriefBankingDetailsDto {
    bankName?: string;
    kvKNumber?: string;
    accountHolderName?: string;
    iban?: string;
}

export class LicencePlateBriefResponse implements ILicencePlateBriefResponse {
    licencePlate?: string;

    constructor(data?: ILicencePlateBriefResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.licencePlate = _data["licencePlate"];
        }
    }

    static fromJS(data: any): LicencePlateBriefResponse {
        data = typeof data === 'object' ? data : {};
        let result = new LicencePlateBriefResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["licencePlate"] = this.licencePlate;
        return data;
    }
}

export interface ILicencePlateBriefResponse {
    licencePlate?: string;
}

export class VehicleInformationResponse implements IVehicleInformationResponse {
    cardInfo?: string[][];
    data?: VehicleInformationSection[];

    constructor(data?: IVehicleInformationResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["cardInfo"])) {
                this.cardInfo = [] as any;
                for (let item of _data["cardInfo"])
                    this.cardInfo!.push(item);
            }
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(VehicleInformationSection.fromJS(item));
            }
        }
    }

    static fromJS(data: any): VehicleInformationResponse {
        data = typeof data === 'object' ? data : {};
        let result = new VehicleInformationResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.cardInfo)) {
            data["cardInfo"] = [];
            for (let item of this.cardInfo)
                data["cardInfo"].push(item);
        }
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item.toJSON());
        }
        return data;
    }
}

export interface IVehicleInformationResponse {
    cardInfo?: string[][];
    data?: VehicleInformationSection[];
}

export class VehicleInformationSection implements IVehicleInformationSection {
    title?: string;
    values?: string[][];

    constructor(data?: IVehicleInformationSection) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            if (Array.isArray(_data["values"])) {
                this.values = [] as any;
                for (let item of _data["values"])
                    this.values!.push(item);
            }
        }
    }

    static fromJS(data: any): VehicleInformationSection {
        data = typeof data === 'object' ? data : {};
        let result = new VehicleInformationSection();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        if (Array.isArray(this.values)) {
            data["values"] = [];
            for (let item of this.values)
                data["values"].push(item);
        }
        return data;
    }
}

export interface IVehicleInformationSection {
    title?: string;
    values?: string[][];
}

export class WeatherForecast implements IWeatherForecast {
    date?: Date;
    temperatureC?: number;
    temperatureF?: number;
    summary?: string | undefined;

    constructor(data?: IWeatherForecast) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.temperatureC = _data["temperatureC"];
            this.temperatureF = _data["temperatureF"];
            this.summary = _data["summary"];
        }
    }

    static fromJS(data: any): WeatherForecast {
        data = typeof data === 'object' ? data : {};
        let result = new WeatherForecast();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["temperatureC"] = this.temperatureC;
        data["temperatureF"] = this.temperatureF;
        data["summary"] = this.summary;
        return data;
    }
}

export interface IWeatherForecast {
    date?: Date;
    temperatureC?: number;
    temperatureF?: number;
    summary?: string | undefined;
}

export class SwaggerException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}