trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:OutDir="$(build.artifactStagingDirectory)\\"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    name: 'PublishBuildArtifacts'
    displayName: 'Create Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Latest Deploy'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Niek Tuijtel(c01f95dd-b3fa-4a0e-a85c-5b68a7d4270e)'
      appType: 'webAppLinux'
      appName: 'autohelper-hangfire'
      deployToSlotOrASE: true
      resourceGroupName: 'AutoHelper'
      slotName: 'production'
      package: '$(Build.ArtifactStagingDirectory)'
      runtimeStack: 'DOTNETCORE|7.0'
      startUpCommand: 'dotnet AutoHelper.Hangfire.Dashboard.dll'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Niek Tuijtel(c01f95dd-b3fa-4a0e-a85c-5b68a7d4270e)'
      appType: 'webAppLinux'
      appName: 'autohelper-webui'
      deployToSlotOrASE: true
      resourceGroupName: 'AutoHelper'
      slotName: 'production'
      package: '$(Build.ArtifactStagingDirectory)'
      runtimeStack: 'DOTNETCORE|7.0'
      startUpCommand: 'dotnet AutoHelper.WebUI.dll'
  